# Generated by Django 3.0.5 on 2020-05-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploads',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
